# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nudgy' do
  pod 'AppCenter/Crashes', '~> 1.9.0'
  pod 'AppCenter/Analytics', '~> 1.9.0'
  pod 'AppCenterReactNativeShared', '~> 1.8.1'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Nudgy
pod 'Firebase'
pod 'Firebase/Messaging'

  platform :ios, '9.0'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'NudgyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Nudgy-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Nudgy-tvOS

  target 'Nudgy-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
