# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nudgy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Nudgy
pod 'Firebase'
pod 'Firebase/Messaging'

  target 'NudgyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Nudgy-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Nudgy-tvOS

  target 'Nudgy-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
